char text[100] = "";
float desired_temperature = 0;
float temperature = 0;
float pressure = 0;
float error = 0;
float previousError = 0;
float integralError = 0;
float Kp = 1;
float Ki = 1;
float Kd = 1;
float dt = 1;
float pwm_duty;